import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import "./globals.css";
import { WideContextProvider } from "@/lib/contexts/wideContext";

const fontHeading = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-heading",
});

const fontBody = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-body",
});

export const fontBrand = localFont({
  src: "./Peppa Pig.ttf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <WideContextProvider>
        <body
          className={cn(
            "antialiased",
            fontHeading.className,
            fontBody.className,
          )}
        >
          {children}
        </body>
      </WideContextProvider>
    </html>
  );
}
